# Generated by Django 5.0.6 on 2024-06-12 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_game_quantity_giftcard_quantity_alter_game_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='quantity',
            new_name='Cd Keys',
        ),
        migrations.AddField(
            model_name='game',
            name='Steam Gifts',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SteamCDKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('redeemed', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cd_keys', to='products.game')),
            ],
        ),
    ]
