# Generated by Django 5.0.6 on 2024-06-12 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_quantity_game_cd_keys_game_steam_gifts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('redeemed', models.BooleanField(default=False)),
                ('platform', models.CharField(choices=[('PSN', 'Playstation'), ('XBOX/MS', 'Xbox/Microsoft'), ('STEAM', 'Steam'), ('EPIC GAMES', 'Epic Games'), ('ITUNES', 'Itunes')], max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cd_keys', to='products.game')),
            ],
        ),
        migrations.DeleteModel(
            name='SteamCDKey',
        ),
    ]
