# Generated by Django 5.0.6 on 2024-06-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productkey_delete_steamcdkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Cd Keys',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='Steam Gifts',
            field=models.IntegerField(null=True),
        ),
    ]
