# Generated by Django 5.0.6 on 2024-06-17 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_game_cd_keys_alter_game_steam_gifts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GiftcardKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('redeemed', models.BooleanField(default=False)),
                ('giftcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='products.giftcard')),
            ],
        ),
    ]
