# Generated by Django 5.0.6 on 2024-07-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('PSN', 'Playstation'), ('XBOX/MS', 'Xbox/Microsoft'), ('STEAM', 'Steam'), ('EPIC GAMES', 'Epic Games'), ('ITUNES', 'Itunes')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
