# Generated by Django 5.0.6 on 2024-07-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_game_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='platform',
            field=models.CharField(choices=[('Playstation', 'PSN'), ('Xbox', 'XBOX/MS'), ('Steam', 'STEAM'), ('Epic Games', 'EPIC GAMES'), ('Itunes', 'ITUNES')], max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('Playstation', 'PSN'), ('Xbox', 'XBOX/MS'), ('Steam', 'STEAM'), ('Epic Games', 'EPIC GAMES'), ('Itunes', 'ITUNES')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='platform',
            field=models.CharField(choices=[('Playstation', 'PSN'), ('Xbox', 'XBOX/MS'), ('Steam', 'STEAM'), ('Epic Games', 'EPIC GAMES'), ('Itunes', 'ITUNES')], max_length=255),
        ),
        migrations.AlterField(
            model_name='productkey',
            name='platform',
            field=models.CharField(choices=[('Playstation', 'PSN'), ('Xbox', 'XBOX/MS'), ('Steam', 'STEAM'), ('Epic Games', 'EPIC GAMES'), ('Itunes', 'ITUNES')], max_length=100),
        ),
    ]
