# Generated by Django 5.0.7 on 2024-07-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_gameitem_description_giftcard_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameitem',
            name='image',
            field=models.ImageField(default='/static/default-cover.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='image',
            field=models.ImageField(default='/static/default-cover.png', upload_to=''),
        ),
    ]
