# Generated by Django 5.0.7 on 2024-08-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_gameitem_image_alter_giftcard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameitem',
            name='platform',
            field=models.CharField(choices=[('Playstation', 'PSN'), ('Xbox', 'XBOX/MS'), ('Steam', 'STEAM'), ('Epic Games', 'EPIC GAMES'), ('Itunes', 'ITUNES')], default='Steam', max_length=200),
        ),
    ]
